version: '2.1'

services:
    whiteboard-demo-ui:
        container_name: whiteboard-demo-ui
        build:
            context: .
            dockerfile: docker-conf/ui/Dockerfile
        image: whiteboard-demo-ui:latest
        env_file:
            - .env
        command: >
            http-server ./ -p 8980
        depends_on: 
            - whiteboard-demo-proxy
   
    whiteboard-demo-server:
        container_name: whiteboard-demo-server
        build:
            context: .
            dockerfile: docker-conf/whiteboard-server/Dockerfile
        image: whiteboard-demo-server:latest
        env_file:
            - .env
        environment:
            - DB_SERVER=whiteboard-demo-db
        links:
            - whiteboard-demo-db
        volumes:
            - "./whiteboard-images:/srv/map-whiteboard-server/public/images/"

    whiteboard-demo-admin:
        container_name: whiteboard-demo-admin
        build:
            context: .
            dockerfile: docker-conf/whiteboard-admin/Dockerfile
        image: whiteboard-demo-admin:latest
        env_file:
            - .env
        command: >
            node_modules/.bin/ng serve

    whiteboard-demo-db:
        container_name: whiteboard-demo-db
        build:
            context: .
            dockerfile: docker-conf/map-whiteboard-db/Dockerfile
        image: whiteboard-demo-db:latest
        volumes:
            - "whiteboard-demo-mongodb:/data/db"
        env_file:
            - .env
    whiteboard-demo-nginx:
        container_name: whiteboard-demo-nginx
        build:
            context: .
            dockerfile: docker-conf/nginx/Dockerfile
        image: whiteboard-demo-nginx:latest
        ports:
            - "25348:24348"
        env_file:
            - .env
        depends_on: 
            - whiteboard-demo-ui
            - whiteboard-demo-server
            - whiteboard-demo-admin
            - whiteboard-demo-swagger

    whiteboard-demo-proxy:
        container_name: whiteboard-demo-proxy
        build:
            context: .
            dockerfile: docker-conf/proxy/Dockerfile
        image: whiteboard-demo-proxy:latest
        environment:
            NODE_ENV: development
            PROXY_PORT: 8085
        command: >
            node ./proxy.js

    whiteboard-demo-swagger:
        container_name: whiteboard-demo-swagger
        image: swaggerapi/swagger-ui
        ports:
        - 8029:8080
        environment:
            SWAGGER_JSON: /spec/openapi.json
        volumes:
        - "./whiteboard-server-docs:/spec"
volumes:
    whiteboard-demo-mongodb:
